

CREATE TABLE Ejecutivos (
    ID_EJECUTIVO INT PRIMARY KEY,
    NOMBRE_EJECUTIVO VARCHAR(255)
); -- Enlace a Empresa

CREATE TABLE Estudios (
    COD_ESTUDIO INT PRIMARY KEY,
    NOMBRE_EST VARCHAR(100) NOT NULL
); -- Enlace a Empresa y Demanda

CREATE TABLE Eventos (
    CODIGO_EVENTO INT PRIMARY KEY,
    DESCRIPCION_EVENTO VARCHAR(255)
); -- Enlacecon Demanda

CREATE TABLE Deudas(
    TIP_DEUDA INT PRIMARY KEY,
    DESCRIPCION_DEUDA VARCHAR(255) NOT NULL
); -- Enlace con Demanda Prima

CREATE TABLE Estados(
    ID_ESTADO INT PRIMARY KEY,
    DESCRIPCION_ESTADO VARCHAR(255) NOT NULL
); -- Enlace con Empresa y Demanda

CREATE TABLE Ubicacion_Procesos (
    ID_UBIPROCESO INT PRIMARY KEY,
    UBICACION_PROCESO VARCHAR(255) NOT NULL
); -- Enlace con Demanda

CREATE TABLE Registros (
    ID_REGISTRO INT PRIMARY KEY,
    MODO_REGISTRO VARCHAR(5) NOT NULL
); -- Enlace con Demanda (evento)

CREATE TABLE Tipo_Empresas (
    ID_TIPO INT PRIMARY KEY,
    NOMBRE_TIPO VARCHAR(255) NOT NULL
); -- Enlace con Empresa

CREATE TABLE Descripcion_Juzgados (
    ID_DJUZGADO INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION_JUZGADO VARCHAR(255)
); -- Enlace con Juzgado

CREATE TABLE Secretario_Juzgados (
    ID_SJUZGADO INT PRIMARY KEY AUTO_INCREMENT,
    SECRETARIO_JUZGADO VARCHAR(255)
); -- Enlace con Juzgado

CREATE TABLE Juzgados (
    ID_JUZGADO INT PRIMARY KEY AUTO_INCREMENT,
    ID_SJUZGADO INT,
    ID_DJUZGADO INT,
    CODIGO_JUZGADO INT,
    FOREIGN KEY (ID_SJUZGADO) REFERENCES Secretario_Juzgados(ID_SJUZGADO),
    FOREIGN KEY (ID_DJUZGADO) REFERENCES Descripcion_Juzgados(ID_DJUZGADO)
);

CREATE TABLE AFP (
    COD_AFP INT PRIMARY KEY,
    NOMBRE_AFP VARCHAR(255) NOT NULL
); -- Enlace con Demanda y Empres

INSERT INTO Juzgados VALUES (1, null, null, null);

INSERT INTO AFP VALUES (1, 'PRIMA');
INSERT INTO AFP VALUES (2, 'PROFUTURO');

INSERT INTO Deudas VALUES (1, 'DEUDA PRESUNTA POR OMISION');PRESUNTA
INSERT INTO Deudas VALUES (2, 'DEUDA PRESUNTA POR DECLARACION');PRESUNTA
INSERT INTO Deudas VALUES (3, 'DEUDA BAJO PAGO');REAL
INSERT INTO Deudas VALUES (4, 'DEUDA DSP REAL');REAL
INSERT INTO Deudas VALUES (5, 'DEUDA BOLETA');REAL
INSERT INTO Deudas VALUES (6, 'DEUDA REAL POR DECLARACION DEL EMPLEADOR (DPE)');REAL
INSERT INTO Deudas VALUES (7, 'REAL');
INSERT INTO Deudas VALUES (8, 'PRESUNTA');
INSERT INTO Deudas VALUES (9, 'MIXTA');
INSERT INTO Deudas VALUES (12, 'REPRO (FRACCIONAMIENTO)');

INSERT INTO Estados VALUES (1, 'VIGENTE');
INSERT INTO Estados VALUES (2, 'CERRADA');

INSERT INTO Registros VALUES (1, 'IRN');
INSERT INTO Registros VALUES (2, 'CEJ');

INSERT INTO Ubicacion_Procesos VALUES (1, 'ARCHIVO GENERAL');
INSERT INTO Ubicacion_Procesos VALUES (2, 'POOL ASIST. JUDICIAL');
INSERT INTO Ubicacion_Procesos VALUES (3, 'MPU/CDG');
INSERT INTO Ubicacion_Procesos VALUES (4, 'ARCHIVO TRANSITORIO');
INSERT INTO Ubicacion_Procesos VALUES (5, 'ESPECIALISTA');
INSERT INTO Ubicacion_Procesos VALUES (6, 'ARCHIVO MODULAR');

INSERT INTO Tipo_Empresas VALUES (1, 'PRIVADA');
INSERT INTO Tipo_Empresas VALUES (2, 'PUBLICA');

INSERT INTO Eventos VALUES (100, 'DEMANDA PRESENTADA');
INSERT INTO Eventos VALUES (101, 'AMPLIACION DE LA DEMANDA');
INSERT INTO Eventos VALUES (102, 'DEMANDA INADMISIBLE');
INSERT INTO Eventos VALUES (103, 'DEMANDA IMPROCEDENTE');
INSERT INTO Eventos VALUES (104, 'DEMANDA ADMITIDA');
INSERT INTO Eventos VALUES (105, 'CONTRADICCION DE LA DEMANDA');
INSERT INTO Eventos VALUES (106, 'ABSOLUCION DE LA CONTRADICCION');
INSERT INTO Eventos VALUES (107, 'SOLICITUD DE SENTENCIA');
INSERT INTO Eventos VALUES (108, 'SENTENCIA A FAVOR');
INSERT INTO Eventos VALUES (109, 'SENTENCIA EN CONTRA');
INSERT INTO Eventos VALUES (110, 'SENTENCIA CONSENTIDA');
INSERT INTO Eventos VALUES (111, 'APELACION AFP');
INSERT INTO Eventos VALUES (112, 'APELACION EMPLEADOR');
INSERT INTO Eventos VALUES (113, 'JUZGADO CONCEDE APELACION');
INSERT INTO Eventos VALUES (114, 'SENTENCIA DE SEGUNDA INSTANCIA A FAVOR');
INSERT INTO Eventos VALUES (115, 'SENTENCIA DE SEGUNDA INSTANCIA EN CONTRA');
INSERT INTO Eventos VALUES (116, 'AMPLIACION INADMISIBLE');
INSERT INTO Eventos VALUES (117, 'AMPLIACION IMPROCEDENTE');
INSERT INTO Eventos VALUES (118, 'AMPLIACION ADMITIDA');
INSERT INTO Eventos VALUES (119, 'SENTENCIA CONSENTIDA EN CONTRA');
INSERT INTO Eventos VALUES (121, 'SENTENCIA A FAVOR DE DEMANDA AMPLIADA');
INSERT INTO Eventos VALUES (122, 'DEMANDA RETENIDA POR USAR IPC PARA DENUNCIA PENAL');
INSERT INTO Eventos VALUES (123, 'FUNDADA EN PARTE DE LA DEMANDA EN 1ERA INSTANCIA');
INSERT INTO Eventos VALUES (124, 'SENTENCIA CONSENTIDA EN PARTE');
INSERT INTO Eventos VALUES (125, 'FUNDADA EN PARTE DE LA DEMANDA EN 2DA INSTANCIA');
INSERT INTO Eventos VALUES (126, 'RESOLUCION QUE ORDENA REQUERIMIENTO DE PARTIDA');
INSERT INTO Eventos VALUES (131, 'SE DERIVA EXPEDIENTE A JUZGADO COMPETENTE');
-- adicionales
INSERT INTO Eventos VALUES (000, 'OTROS EVENTOS');
INSERT INTO Eventos VALUES (001, 'REQUERIMIENTO DE EMBARGO');
INSERT INTO Eventos VALUES (002, 'REQUERIMIENTO DEL ARTICULO 46');
INSERT INTO Eventos VALUES (003, 'SOLICITUD DE DESARCHIVAMIENTO');
INSERT INTO Eventos VALUES (004, 'DENUNCIA PENAL');

INSERT INTO Estudios VALUES (100, 'FERNANDEZ NUÑEZ ASOC SRL TACNA');
INSERT INTO Estudios VALUES (101, 'FERNANDEZ NUÑEZ ASOC SRL PUNO');
INSERT INTO Estudios VALUES (103, 'FERNANDEZ NUÑEZ ASOC MOQUEGUA');
INSERT INTO Estudios VALUES (122, 'FERNANDEZ NUÑEZ - LA LIBERTAD');

INSERT INTO Ejecutivos VALUES (1,'ANNI PACHECO');
INSERT INTO Ejecutivos VALUES (2,'EDGAR PACHECO');
INSERT INTO Ejecutivos VALUES (3,'ANGEL CORTEZ');
INSERT INTO Ejecutivos VALUES (4, 'MELANIE ESPINOZA');

INSERT INTO Descripcion_Juzgados VALUES (1, 'JLP ASCOPE');
INSERT INTO Descripcion_Juzgados VALUES (2, 'JLP CASCAS');
INSERT INTO Descripcion_Juzgados VALUES (3, 'JLP HUAMACHUCO');
INSERT INTO Descripcion_Juzgados VALUES (4, 'JLP ILO');
INSERT INTO Descripcion_Juzgados VALUES (5, 'JLP JULIACA');
INSERT INTO Descripcion_Juzgados VALUES (6, 'JLP MACUSANI');
INSERT INTO Descripcion_Juzgados VALUES (7, 'JLP MOQUEGUA');
INSERT INTO Descripcion_Juzgados VALUES (8, 'JLP PUNO');
INSERT INTO Descripcion_Juzgados VALUES (9, 'JLP TACNA');
INSERT INTO Descripcion_Juzgados VALUES (10, 'JLP TRUJILLO');

INSERT INTO Secretario_Juzgados VALUES (1, 'ASMAT');
INSERT INTO Secretario_Juzgados VALUES (2, 'ESPINOZA');
INSERT INTO Secretario_Juzgados VALUES (3, 'CORDOVA');
INSERT INTO Secretario_Juzgados VALUES (4, 'MAMANI');
INSERT INTO Secretario_Juzgados VALUES (5, 'CHURA');