
CREATE TABLE Empresas (
    RUC_EMPLEADOR VARCHAR(11) PRIMARY KEY,
    RAZON_SOCIAL VARCHAR(255) NOT NULL,
    ID_TIPO INT NOT NULL,
    DIRECC VARCHAR(255),
    LOCALI VARCHAR(255),
    REFERENCIA VARCHAR(255),
    DISTRITO INT,
    PROVINCIA INT,
    DEPARTAMENTO INT,
    REPRO DECIMAL(10,2),
    FOREIGN KEY (ID_TIPO) REFERENCES Tipo_Empresas(ID_TIPO),
    FOREIGN KEY (DISTRITO) REFERENCES Distritos(ID_DIST),
    FOREIGN KEY (PROVINCIA) REFERENCES Provincias(ID_P),
    FOREIGN KEY (DEPARTAMENTO) REFERENCES Departamentos(ID_D)
);

CREATE TABLE Empresas_RpL (
    ID_REPRESENTANTE INT PRIMARY KEY AUTO_INCREMENT,
    REPRESENTANTE_LEGAL VARCHAR(255) NOT NULL,
    RL_CORREO VARCHAR(255),
    RL_TELEFONO VARCHAR(11),
    RUC_EMPLEADOR VARCHAR(11),
    FOREIGN KEY (RUC_EMPLEADOR) REFERENCES Empresas(RUC_EMPLEADOR)
);

CREATE TABLE Empresas_Datos(
    RUC_EMPLEADOR VARCHAR(11),
    TELEFONO VARCHAR(11),
    CORREO VARCHAR(255),
    NOMBRE VARCHAR(255),
    FOREIGN KEY (RUC_EMPLEADOR) REFERENCES Empresas(RUC_EMPLEADOR)
);

CREATE TABLE Empresas_Estudios(
    RUC_EMPLEADOR VARCHAR(11),
    COD_ESTUDIO INT,
    ID_EJECUTIVO INT,
    ID_ESTADO INT,
    COD_AFP INT,
    FOREIGN KEY (COD_AFP) REFERENCES AFP(COD_AFP),
    FOREIGN KEY (RUC_EMPLEADOR) REFERENCES Empresas(RUC_EMPLEADOR),
    FOREIGN KEY (COD_ESTUDIO) REFERENCES Estudios(COD_ESTUDIO),
    FOREIGN KEY (ID_EJECUTIVO) REFERENCES Ejecutivos(ID_EJECUTIVO),
    FOREIGN KEY (ID_ESTADO) REFERENCES Estados(ID_ESTADO)
);

CREATE TABLE Registros_Correo (
    ID_CORREO INT PRIMARY KEY AUTO_INCREMENT,
    RUC_EMPLEADOR VARCHAR(11),
    FECHA DATE,
    FOREIGN KEY (RUC_EMPLEADOR) REFERENCES Empresas(RUC_EMPLEADOR)
);

CREATE TABLE DemandasPrima (
    ID_DEMANDAP INT PRIMARY KEY AUTO_INCREMENT,
    NR_DEMANDA VARCHAR(15) NOT NULL,
    FE_EMISION DATE NOT NULL,
    RUC_EMPLEADOR VARCHAR(11) NOT NULL,
    COD_ESTUDIO INT NOT NULL,
    MTO_TOTAL_DEMANDA DECIMAL(10,2),
    CODIGO_UNICO_EXPEDIENTE VARCHAR(26),
    FECHA_PRESENTACION DATE,
    EXPEDIENTE INT,
    AÑO INT,
    ID_JUZGADO INT,
    FOREIGN KEY (RUC_EMPLEADOR) REFERENCES Empresas(RUC_EMPLEADOR),
    FOREIGN KEY (COD_ESTUDIO) REFERENCES Estudios(COD_ESTUDIO),
    FOREIGN KEY (ID_JUZGADO) REFERENCES Juzgados(ID_JUZGADO)
);

CREATE TABLE DemandasPrima_Deudas (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_DEMANDAP INT,
    TIP_DEUDA INT,
    FOREIGN KEY (ID_DEMANDAP) REFERENCES DemandasPrima(ID_DEMANDAP),
    FOREIGN KEY (TIP_DEUDA) REFERENCES Deudas(TIP_DEUDA)
);

CREATE TABLE DemandasProfuturo (
    ID_DEMANDAPRO INT PRIMARY KEY AUTO_INCREMENT,
    RUC_EMPLEADOR VARCHAR(11) NOT NULL,
    FE_EMISION DATE NOT NULL,
    COD_ESTUDIO INT NOT NULL,
    TOTAL_DEMANDADO DECIMAL(10,2),
    TIP_DEUDA INT,
    NOMBRE_EST VARCHAR(255) NOT NULL,
    CODIGO_UNICO_EXPEDIENTE VARCHAR(26),
    FECHA_PRESENTACION DATE,
    NRO_EXPEDIENTE INT,
    AÑO INT,
    CODIGO_JUZGADO INT,
    ID_SJUZGADO INT,
    ID_DJUZGADO INT,
    FOREIGN KEY (TIP_DEUDA) REFERENCES Deudas(TIP_DEUDA),
    FOREIGN KEY (RUC_EMPLEADOR) REFERENCES Empresas(RUC_EMPLEADOR),
    FOREIGN KEY (ID_SJUZGADO) REFERENCES Secretario_Juzgados(ID_SJUZGADO),
    FOREIGN KEY (ID_DJUZGADO) REFERENCES Descripcion_Juzgados(ID_DJUZGADO)
);

CREATE TABLE DemandasProfuturo_Numero (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_DEMANDAPRO INT,
    NUM_DEMANDA VARCHAR(15) NOT NULL,
    FOREIGN KEY (ID_DEMANDAPRO) REFERENCES DemandasProfuturo(ID_DEMANDAPRO)
);

CREATE TABLE Demandas (
    ID_DEMANDA INT PRIMARY KEY AUTO_INCREMENT,
    COD_AFP INT NOT NULL,
    ID_DEMANDAP INT,
    ID_DEMANDAPRO INT,
    ID_ESTADO INT,
    ID_UBIPROCESO INT,
    FOREIGN KEY (ID_UBIPROCESO) REFERENCES Ubicacion_Procesos(ID_UBIPROCESO),
    FOREIGN KEY (COD_AFP) REFERENCES AFP(COD_AFP),
    FOREIGN KEY (ID_ESTADO) REFERENCES Estados(ID_ESTADO),
    FOREIGN KEY (ID_DEMANDAP) REFERENCES DemandasPrima(ID_DEMANDAP),
    FOREIGN KEY (ID_DEMANDAPRO) REFERENCES DemandasProfuturo(ID_DEMANDAPRO)
);



CREATE TABLE Eventos_DemandasPrima (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_DEMANDAP INT NOT NULL,
    CODIGO_EVENTO INT NOT NULL,
    RESOLUCION INT NOT NULL,
    FECHA_EVENTO DATE NOT NULL,
    ID_REGISTRO INT NOT NULL,
    ID_UBIPROCESO INT,
    OBSERVACIONES VARCHAR(255),
    FOREIGN KEY (ID_UBIPROCESO) REFERENCES Ubicacion_Procesos(ID_UBIPROCESO),
    FOREIGN KEY (ID_REGISTRO) REFERENCES Registros(ID_REGISTRO),
    FOREIGN KEY (ID_DEMANDAP) REFERENCES DemandasPrima(ID_DEMANDAP),
    FOREIGN KEY (CODIGO_EVENTO) REFERENCES Eventos(CODIGO_EVENTO)
);

CREATE TABLE Eventos_DemandasProfuturo (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_DEMANDAPRO INT NOT NULL,
    RESOLUCION INT NOT NULL,
    CODIGO_EVENTO INT NOT NULL,
    FECHA_EVENTO DATE NOT NULL,
    ID_REGISTRO INT NOT NULL,
    ID_UBIPROCESO INT,
    OBSERVACIONES VARCHAR(255),
    FOREIGN KEY (ID_UBIPROCESO) REFERENCES Ubicacion_Procesos(ID_UBIPROCESO),
    FOREIGN KEY (ID_REGISTRO) REFERENCES Registros(ID_REGISTRO),
    FOREIGN KEY (ID_DEMANDAPRO) REFERENCES DemandasProfuturo(ID_DEMANDAPRO),
    FOREIGN KEY (CODIGO_EVENTO) REFERENCES Eventos(CODIGO_EVENTO)

);

CREATE TABLE Actividades (
    ID_ACTIVIDAD INT PRIMARY KEY AUTO_INCREMENT,
    ID_DEMANDAP INT,
    ID_DEMANDAPRO INT,
    ID_EVENTO INT,
    ID_USUARIO INT,
    ACTIVIDAD VARCHAR(255),
    FOREIGN KEY (ID_DEMANDAP) REFERENCES DemandasPrima(ID_DEMANDAP),
    FOREIGN KEY (ID_DEMANDAPRO) REFERENCES DemandasProfuturo(ID_DEMANDAPRO),
    FOREIGN KEY (ID_EVENTO) REFERENCES Eventos(CODIGO_EVENTO)
);

CREATE TABLE Administraciones (
    ID_ADMINISTRACION INT PRIMARY KEY AUTO_INCREMENT,
    FECHA DATE,
    ZONA VARCHAR(255),
    AFP VARCHAR(255),
    CODIGO_FACTURA VARCHAR(255),
    RECIBO VARCHAR(255),
    SUBTOTAL DECIMAL(10,2),
    IGV DECIMAL(10,2),
    TOTAL_RECIBO DECIMAL(10,2),
    DETRACCION DECIMAL(10,2),
    RUC_EMPLEADOR VARCHAR(11),
    COMISION DECIMAL(10,2),
    EJECUTIVA VARCHAR(255),
    ARANCELES DECIMAL(10,2),
    ID_DEMANDAP INT,
    ID_DEMANDAPRO INT,
    MON_MET_INTERNA DECIMAL(10,2),
    MONTO_TOTAL DECIMAL(10,2),
    BANCO VARCHAR(255),
    DEP_DETRACCION DECIMAL(10,2),
    OBSERVACIONES VARCHAR(255),
    RECIBO_FACTURA VARCHAR(255),
    ESTADO VARCHAR(255),
    FOREIGN KEY (ID_DEMANDAP) REFERENCES DemandasPrima(ID_DEMANDAP),
    FOREIGN KEY (ID_DEMANDAPRO) REFERENCES DemandasProfuturo(ID_DEMANDAPRO),
    FOREIGN KEY (RUC_EMPLEADOR) REFERENCES Empresas(RUC_EMPLEADOR)
);